version: "3"
services:
  spider:
    build: .
    env_file:
      - .env
    container_name: justice-archive
    environment:
      VIRTUAL_HOST: spider.justice.docker
      VIRTUAL_PORT: "8081"
    volumes:
      - ./snapshots:/archiver/snapshots
    ports:
      - "8081:8080"
