apiVersion: v1
kind: Service
metadata:
  name: justice-gov-uk-archiver-service
  labels:
    app: justice-gov-uk-archiver-dev
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: justice-gov-uk-archiver-dev
